# Generated by Django 5.1.1 on 2024-10-18 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='descripcion',
        ),
    ]
